services:
  database:
    image: postgis/postgis
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}

  app:
    build:
      context: .
    ports:
      - "8000:8000"
    volumes:
      - .:/vaedo
    command: >
      sh -c "python manage.py runserver 0.0.0.0:8000"
    depends_on:
      - database
